apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: amir2023/customerserver:latest
        ports:
        - containerPort: 3001
        env:
          - name: DATABASE_URL
            value: "mongodb://mongodb.default.svc.cluster.local"
          - name: MONGODB_USER
            value: "root"
          - name: MONGODB_PASSWORD
            value: "123"
          - name: KAFKA_PASSWORD
            value: "123"
          - name: KAFKA_USERNAME
            value: "user1"