apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: server-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: node-app-deployment
  minReplicaCount: 2
  maxReplicaCount: 5
  cooldownPeriod: 30
  pollingInterval: 15
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-server.default.svc.cluster.local  # Replace with your Prometheus service address
      metricName: http_request_duration_seconds_bucket
      threshold: "2"  # Set the threshold value
      query: | 
        sum(http_request_duration_seconds_bucket{le="0.1"} ) - sum(http_request_duration_seconds_bucket{le="0.01"} ) 
